e_commerce/commen/urls.py
from django.urls import path
from . import views

app_name = 'commen'

urlpatterns = [
    path('project_home', views.project_home, name='project_home'),
    path('customer_sign', views.customer_sign, name='customer_sign'),
    path('customer_login', views.customer_login, name="customer_login"),
    path('seller_sign', views.seller_sign, name="seller_sign"),
    path('seller_login', views.seller_login, name='seller_login'),
    path('email_exist',views.email_exist,name='email_exist')
]

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('commen/',include ('commen.urls')),
    path('e_admin/',include('e_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/commen/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    customer_name = models.CharField(max_length= 50)
    customer_phone = models.CharField(max_length= 20)
    customer_mail = models.CharField(max_length= 100)
    customer_image = models.ImageField(upload_to='customer/')
    customer_password = models.CharField(max_length=15)
    customer_addres = models.CharField(max_length= 500)

    class Meta:
        db_table ='customer_tb'

class Seller(models.Model):
    seller_first_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    mail = models.CharField(max_length=50)
    company_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='seller/')
    ac_number = models.BigIntegerField()
    ifsc = models.CharField(max_length=20)
    account_holder = models.CharField(max_length=30)
    branch = models.CharField(max_length=30)
    address = models.CharField(max_length=500)
    user_name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    class Meta:
        db_table ='seller_tb'

e_commerce/commen/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect

# class importing here
from commen.models import Customer, Seller

# user pass auto genarationg bilting function
# to send the genarated pass in email 
from django.core.mail import send_mail


from django.conf import settings

import random

# Create your views here.

def project_home(request):
    return render(request, 'commen_templates/project_home.html')



def customer_sign(request):
    # get values by input area and store the values in a variable
    if request.method == 'POST':
        customer_name = request.POST['db_name']
        customer_phone = request.POST['db_phone']
        customer_mail = request.POST['db_mail']
        customer_image = request.FILES['db_image']
        customer_password = request.POST['db_password']
        customer_addres = request.POST['db_addres']
        # stored veriable values assign the class veriable(db column) db veriale = created veriable
        new_customer = Customer(
            customer_name = customer_name,
            customer_phone = customer_phone,
            customer_mail= customer_mail,
            customer_image = customer_image,
            customer_password= customer_password,
            customer_addres= customer_addres
        )     
        # save the all values in a new veriable  
        new_customer.save()

    
    return render(request, 'commen_templates/customer_sign.html')



def customer_login(request):
    # exaption message
    msg = ''
    # customer login time get the values mail&pass and store the values in veriable
    if request.method == 'POST':
        cust_mail = request.POST['db_mail']
        cust_password = request.POST['db_password']
        # stored values cross check by the clss veriable(checked with db values)
        try:
            customer = Customer.objects.get(customer_mail = cust_mail,customer_password = cust_password)
            request.session['customer'] = customer.id
            # if conditon match return work 
            return redirect('customer:customer_home')
        # condition false msg return(exaption)
        except:
            msg = 'invalid password or mail'

    return render(request, 'commen_templates/customer_login.html',{'msg':msg})




def seller_sign(request):
    if request.method == 'POST':
        fname = request.POST['s_name']
        phone = request.POST['s_phone']
        mail = request.POST['s_mail']
        cname = request.POST['s_cname']
        image = request.FILES['s_image']
        acnumber = request.POST['s_acnumber']
        ifsc = request.POST['s_ifsc']
        account_holder = request.POST['s_acholdername']
        branch = request.POST['s_branch']
        address = request.POST['s_address']
        s_username = random.randint(1111,9999)
        s_pass = 'sel-' + fname.lower() + str(s_username)
        message = 'Hii your username is :' + str(s_username) + 'temporary password is ' + s_pass 

        new_seller = Seller(
            seller_first_name = fname,
            phone = phone,
            mail = mail, 
            company_name = cname,
            image = image,
            ac_number = acnumber,
            ifsc = ifsc,
            account_holder = account_holder,
            branch = branch,
            address = address,
            user_name = s_username,
            password = s_pass
        )
        send_mail(
            'user name and temporary password',
            message,
            settings.EMAIL_HOST_USER,
            [mail],
            fail_silently = False
        )
        new_seller.save()

    return render(request, 'commen_templates/seller_sign.html')




def seller_login(request):
    msg = ''
    if request.method == 'POST':
        seller_username = request.POST['s_username']
        seller_password = request.POST['s_password']
        try:
            seller = Seller.objects.get(user_name = seller_username,password = seller_password)
            request.session['seller'] = seller.id
            return redirect('seller:seller_home')

        except:
            msg = 'invalid pass or username'

    return render(request, 'commen_templates/seller_login.html',{'msg':msg})

def email_exist(request):
    
    email = request.POST['email']
    status = Customer.objects.filter(customer_mail = email).exists()
    return JsonResponse({'status':status})

e_commerce/commen/templates/commen_templates/customer_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COSTUMER LOGIN</title>
    <link rel="stylesheet" href="{% static 'css/customer_login.css' %}">
</head>

<body>
    <div class="container">
        <div class="box">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <th>COSTUMER LOGIN</th>
                    </tr>
                    <tr>
                        <td>
                            <input type="email" placeholder="E-mail" name="db_mail">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="password" placeholder="Password" name="db_password">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a id="forgot" href=""><b>Forgot password ?</b></a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit">
                            {{msg}}
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="container">
        <b id="back"><a href="{% url 'commen:project_home' %}">BACK TO HOME PAGE</a></b>
    </div>
</body>

</html>

e_commerce/commen/templates/commen_templates/customer_sign.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>customer SIGN</title>
    <link rel="stylesheet" href="{% static 'css/customer_sign.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

</head>

<body>

    <div class="container">
        <div class="box">
            <h3>COSTOMER SIGN</h3>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>
                            <input type="text" placeholder="First Name" name="db_name">
                        </td>
                    </tr>

                    <tr>
                        <td colspan="2">
                            <input type="number" placeholder="Phone" name="db_phone">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="email" placeholder="E-mail" name="db_mail" id="email">
                            <span id="span"></span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>image</b><input type="file" name="db_image">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="password" placeholder="Password" name="db_password">
                        </td>

                    </tr>
                    <tr>
                        <th>
                            <textarea name="db_addres" id="" cols="56" rows="4" placeholder="Enter address"></textarea>
                        </th>
                    </tr>
                    <tr>
                        <th>
                            <input type="submit" id="btn">
                        </th>
                    </tr>
                </table>
            </form>

        </div>
    </div>
    <div class="container">
        <b><a href="{% url 'commen:project_home' %}">BACK TO HOME PAGE</a></b>
    </div>

    <script>
        $('#email').change(function () {
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()  //passing csrf token in ajax request
                }
            })

            $.ajax({
                url: "{% url 'commen:email_exist' %}",  // url in which ajax call is made
                type: 'POST',  //method in which data is send
                data: {
                    email: $(this).val()  //sending data in json fromat here, key is email
                },
                success: function (response) {
                    console.log(response.status)
                    if(response.status == true){
                        $('#span').html('Email Already Exist')
                    }

                    alert('email id already exists')
                }
            })
            
        })
    </script>

</body>

</html>

e_commerce/commen/templates/commen_templates/project_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/project_home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>HOME PAGE</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">SHOPPING</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'commen:customer_login' %}">COSTUMER-LOGIN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'commen:customer_sign' %}">COSTUMER-SIGN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'commen:seller_login' %}">SELLER-LOGIN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'commen:seller_sign' %}">SELLER-SIGN</a>
                    </li>

                </ul>

                </ul>
            </div>
        </div>
    </nav>



</body>

</html>

e_commerce/commen/templates/commen_templates/seller_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SELLER LOGIN</title>
    <link rel="stylesheet" href="{% static 'css/seller_login.css' %}">
</head>
<body>
    <div class="container">
        <div class="box">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>
                            {{msg}}
                        </td>
                    </tr>
                    <tr>
                        <th>SELLER LOGIN</th>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" placeholder="user nmae" name="s_username">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="password" placeholder="Password" name="s_password">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a id="forgot" href=""><b>Forgot password ?</b></a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="container">
        <b id="back"><a href="{% url 'commen:project_home' %}">BACK TO HOME PAGE</a></b>
    </div>
</body>
</html>

e_commerce/commen/templates/commen_templates/seller_sign.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SELLER SIGN</title>
    <link rel="stylesheet" href="{% static 'css/seller_sign.css' %}">
</head>

<body>
    <div class="container">
        <div class="box">
            <h3>SELLER SIGN</h3>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <td colspan="2">
                            <input type="text" placeholder="First Name" name="s_name">
                        </td>
                        
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="number" placeholder="Phone" name="s_phone">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="email" placeholder="E-mail" name="s_mail">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="text" placeholder="Company name" name="s_cname">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="file" name="s_image">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="number" placeholder="Account number" name="s_acnumber">
                        </td>
                        <td>
                            <input type="text" placeholder="IFSC" name="s_ifsc">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" placeholder="AC/holder name" name="s_acholdername">
                        </td>
                        <td>
                            <input type="text" placeholder="Branch" name="s_branch">
                        </td>
                    </tr>
                    <tr>
                        <th colspan="2">
                            <textarea name="s_address" id="" cols="56" rows="4" placeholder="Enter address"></textarea>
                        </th>
                    </tr>
                    <tr>
                        <th colspan="2"><input type="submit" name="" id="btn"></th>
                    </tr>
                </table>
            </form>

        </div>
    </div>
    <div class="container">
        <b><a href="{% url 'commen:project_home' %}">BACK TO HOME PAGE</a></b>
    </div>

</body>

</html>