e_commerce/commen/urls.py
from django.urls import path
from . import views

app_name = 'commen'

urlpatterns = [
    path('project_home', views.project_home, name='project_home'),
    path('customer_sign', views.customer_sign, name='customer_sign'),
    path('customer_login', views.customer_login, name="customer_login"),
    path('seller_sign', views.seller_sign, name="seller_sign"),
    path('seller_login', views.seller_login, name='seller_login'),
    path('email_exist',views.email_exist,name='email_exist')
]

e_commerce/e_admin/urls.py
from django.urls import path
from . import views

app_name = 'e_admin'

urlpatterns = [
    path('e_admin_home',views.e_admin_home, name = "e_admin_home"),
    path('approve_seller',views.approve_seller, name="approve_seller"),
    path('view_seller',views.view_seller, name="view_seller"),
    path('view_costumer',views.view_costumer,name="view_costumer"),
    path('admin_login',views.admin_login, name="admin_login")
]

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('commen/',include ('commen.urls')),
    path('e_admin/',include('e_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/e_admin/models.py
from django.db import models

# Create your models here.

e_commerce/e_admin/views.py
from django.shortcuts import render

# Create your views here.

def e_admin_home(request):
    return render(request, 'e_admin_templates/e_admin_home.html')

def approve_seller(request):
    return render(request, 'e_admin_templates/approve_seller.html')

def view_seller(request):
    return render(request, 'e_admin_templates/view_seller.html')

def view_costumer(request):
    return render(request, 'e_admin_templates/view_costumer.html')

def admin_login(request):
    return render(request, 'e_admin_templates/admin_login.html')

e_commerce/e_admin/templates/e_admin_templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADMIN LOGIN</title>
    <link rel="stylesheet" href="{% static 'css/admin_login.css' %}">
</head>
<body>
    <div class="container">
        <div class="box">
            <form action="">
                <table>
                    <tr>
                        <th>ADMIN LOGIN</th>
                    </tr>
                    <tr>
                        <td>
                            <input type="email" placeholder="E-mail">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="password" placeholder="Password">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a id="forgot" href=""><b>Forgot password ?</b></a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="container">
        <b id="back"><a href="{% url 'e_admin:e_admin_home' %}">BACK TO HOME PAGE</a></b>
    </div>
</body>
</html>

e_commerce/e_admin/templates/e_admin_templates/approve_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/approve_seller.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>APPROVE SELLER</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">APPROVE SELLER</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:e_admin_home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:approve_seller' %}">APPROVE SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_seller' %}">VIEW SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_costumer' %}">VIEW COSTUMER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:admin_login' %}">LOGIN</a>
                    </li> 
                 </ul>
            </div>
        </div>
    </nav>

    <table class="table1">
        <tr>
            <th>S NO</th>
            <th>Name</th>
            <th>Email</th>
            <th>Account No</th>
            <th>IFSC</th>
            <th>Companey Name</th>
            <th>Phone</th>
            <th>Action</th>
        </tr>
      
    </table>




</body>

</html>

e_commerce/e_admin/templates/e_admin_templates/e_admin_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/e_admin_home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>admin home</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">ADMIN HOME</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:e_admin_home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:approve_seller' %}">APPROVE SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_seller' %}">VIEW SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_costumer' %}">VIEW COSTUMER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:admin_login' %}">LOGIN</a>
                    </li>

                </ul>
                
            </div>
        </div>
    </nav>

</body>

</html>

e_commerce/e_admin/templates/e_admin_templates/view_costumer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/view_costumer.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>view costumerr</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">VIEW COSTUMER</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:e_admin_home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:approve_seller' %}">APPROVE SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_seller' %}">VIEW SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_costumer' %}">VIEW COSTUMER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:admin_login' %}">LOGIN</a>
                    </li>

                </ul>
                
            </div>
        </div>
    </nav>

    <table class="table1">
        <tr>
            <th>S NO</th>
            <th>Name</th>
            <th>Email</th>
            <th>Account No</th>
            <th>IFSC</th>
            <th>Company name</th>
            <th>Phone</th>
        </tr>
      
    </table>

e_commerce/e_admin/templates/e_admin_templates/view_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/view_seller.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>view seller</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">VIEW SELLER</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:e_admin_home' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:approve_seller' %}">APPROVE SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_seller' %}">VIEW SELLER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:view_costumer' %}">VIEW COSTUMER</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'e_admin:admin_login' %}">LOGIN</a>
                    </li>

                </ul>
                
            </div>
        </div>
    </nav>

    <table class="table1">
        <tr>
            <th>S NO</th>
            <th>Name</th>
            <th>Email</th>
            <th>Account No</th>
            <th>IFSC</th>
            <th>Company name</th>
            <th>Phone</th>
        </tr>
      
    </table>



















</body>






</html>