e_commerce/commen/urls.py
from django.urls import path
from . import views

app_name = 'commen'

urlpatterns = [
    path('project_home', views.project_home, name='project_home'),
    path('customer_sign', views.customer_sign, name='customer_sign'),
    path('customer_login', views.customer_login, name="customer_login"),
    path('seller_sign', views.seller_sign, name="seller_sign"),
    path('seller_login', views.seller_login, name='seller_login'),
    path('email_exist',views.email_exist,name='email_exist')
]

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('commen/',include ('commen.urls')),
    path('e_admin/',include('e_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/seller/urls.py
from django.urls import path
from . import views

app_name = "seller"

urlpatterns = [
    path('seller_home',views.seller_home, name="seller_home"),
    path('product_catelogue',views.product_catelogue,name = "product_catelogue"),
    path('add_product',views.add_product, name="add_product"),
    path('change_password', views.change_password, name="change_password"),
    path('update_stock',views.update_stock , name="update_stock"),
    path('order_history', views.order_history, name="order_history"),
    path('seller_profile',views.seller_profile, name="seller_profile"),
    path('logout',views.logout,name="logout")
]

e_commerce/seller/models.py
from django.db import models

from commen.models import Seller

# Create your models here.

class Product(models.Model):
    seller = models.ForeignKey(Seller,on_delete=models.CASCADE)
    product_id = models.CharField(max_length=100)
    product_name =models.CharField(max_length=100)
    discription =  models.CharField(max_length=500)
    stock = models.BigIntegerField()
    price = models.BigIntegerField()
    image = models.ImageField(upload_to='product/')

    class meta:
        db_table = 'product'

e_commerce/seller/views.py
from django.shortcuts import render,redirect

from commen.models import Seller
from seller.models import Product



# Create your views here.

def seller_home(request):

    seller_data = Seller.objects.get(id=request.session['seller'])

    return render(request, 'seller_templates/seller_home.html',{'data':seller_data})

def product_catelogue(request):
    product_data = Product.objects.filter(seller_id=request.session['seller'])
    return render(request, 'seller_templates/product_catelogue.html',{'p_data':product_data})

def add_product(request):
    msg =''
    if request.method == 'POST':

        p_id = request.POST['product_id']
        p_name = request.POST['product_name']
        p_discription = request.POST['discription']
        stock = request.POST['stock']
        price = request.POST['price']
        image = request.FILES['image']

        add_product = Product(
        seller_id = request.session['seller'],
        product_id = p_id,
        product_name = p_name,
        discription = p_discription,
        stock = stock,
        price = price,
        image = image

        )
        add_product.save()
        msg = 'add product successfull'

    return render(request, 'seller_templates/add_product.html',{'mag':msg})

def change_password(request):
    return render(request, 'seller_templates/change_password.html')

def update_stock(request):
    return render(request, 'seller_templates/update_stock.html')

def order_history(request):
    return render(request, 'seller_templates/order_history.html')

def seller_profile(request):
    seller_data = Seller.objects.get(id=request.session['seller'])

    return render(request, 'seller_templates/seller_profile.html',{'data':seller_data})

def logout(request):
    del request.session['seller']
    request.session.flush()
    return redirect('commen:project_home')

e_commerce/seller/templates/seller_templates/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add product</title>
    <link rel="stylesheet" href="{% static 'css/add_product.css' %}">
</head>

<body>
    <div class="main">

        <div class="container_left">
            <div class="sub">
                <h2>MENU</h2>
            </div>
            <div class="sub"><a href="{% url 'seller:seller_home' %}">Home</a></div>
            <div class="sub"><a href="{% url 'seller:product_catelogue' %}">Product Catelogue</a></div>
            <div class="sub"><a href="{% url 'seller:add_product' %}">Add Product</a></div>
            <div class="sub"><a href="{% url 'seller:change_password' %}">Change Password</a></div>
            <div class="sub"><a href="{% url 'seller:seller_profile' %}">Profile</a></div>
            <div class="sub"><a href="">Recent Orders</a></div>
            <div class="sub"><a href="{% url 'seller:update_stock' %}">Update Stock</a></div>
            <div class="sub"><a href="{% url 'seller:order_history' %}">Order History</a></div>
        </div>
        <div class="container_right">
            <div class="seller_name">
                <h3>ADD PRODUCT</h3>
            </div>
            <div class="add">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table_add">
                        <tr>
                            <td>
                                <h3>{{msg}}</p3>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="text" placeholder="PRODUCT ID" name="product_id">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="text" placeholder="Product Name" name="product_name">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <textarea name="discription" id="" cols="50" rows="6" placeholder="Discription"></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="number" placeholder="stock" name="stock">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="number" placeholder="Price" name="price">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="file" name="image">
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input id="btn" type="submit">
                            </td>
                        </tr>
                    </table>
                </form>



            </div>








        </div>
    </div>

</body>

</html>

e_commerce/seller/templates/seller_templates/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SELLER PASSWORD CHANGE</title>
    <link rel="stylesheet" href="{% static 'css/change_password.css' %}">
</head>
<body>
    <div class="container">
        <div class="box">
            <form action="">
                <table>
                    <tr>
                        <th>SELLER PASSWORD CHANGE</th>
                    </tr>
                    <tr>
                        <td>
                            <input type="email" placeholder="E-mail">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="number" placeholder="Phone">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="container">
        <b id="back"><a href="{% url 'seller:seller_home' %}">BACK TO HOME PAGE</a></b>
    </div>
</body>
</html>

e_commerce/seller/templates/seller_templates/order_history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORDER HISTORY</title>
    <link rel="stylesheet" href="{% static 'css/order_history.css' %}">
</head>

<body>
    <div class="main">
    
        <div class="container_left">
            <div class="sub">
                <h2>MENU</h2>
            </div>
            <div class="sub"><a href="{% url 'seller:seller_home' %}">Home</a></div>
            <div class="sub"><a href="{% url 'seller:product_catelogue' %}">Product Catelogue</a></div>
            <div class="sub"><a href="{% url 'seller:add_product' %}">Add Product</a></div>
            <div class="sub"><a href="{% url 'seller:change_password' %}">Change Password</a></div>
            <div class="sub"><a href="{% url 'seller:seller_profile' %}">Profile</a></div>
            <div class="sub"><a href="">Recent Orders</a></div>
            <div class="sub"><a href="{% url 'seller:update_stock' %}">Update Stock</a></div>
            <div class="sub"><a href="{% url 'seller:order_history' %}">Order History</a></div>
        </div>
        <div class="container_right">
            <div class="seller_name">
                <h3>ORDER HISTORY</h3>
            </div>
            
          
               
               

              
            








        </div>
    </div>
    
</body>

</html>

e_commerce/seller/templates/seller_templates/product_catelogue.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>product_catelogue</title>
    <link rel="stylesheet" href="{% static 'css/product_catelogue.css' %}">
</head>

<body>
    <div class="main">
    
        <div class="container_left">
            <div class="sub">
                <h2>MENU</h2>
            </div>
            <div class="sub"><a href="{% url 'seller:seller_home' %}">Home</a></div>
            <div class="sub"><a href="{% url 'seller:product_catelogue' %}">Product Catelogue</a></div>
            <div class="sub"><a href="{% url 'seller:add_product' %}">Add Product</a></div>
            <div class="sub"><a href="{% url 'seller:change_password' %}">Change Password</a></div>
            <div class="sub"><a href="{% url 'seller:seller_profile' %}">Profile</a></div>
            <div class="sub"><a href="">Recent Orders</a></div>
            <div class="sub"><a href="{% url 'seller:update_stock' %}">Update Stock</a></div>
            <div class="sub"><a href="{% url 'seller:order_history' %}">Order History</a></div>
        </div>
        <div class="container_right">
            <div class="seller_name">
                <h3>PRODUCT CATALOGUE</h3>
            </div>
            
            <div class="product">
               {% for i in p_data %}
                <div class="card">
                    <div class="b_image">
                        <img src="{{i.image.url}}" alt="">
                    </div>
                    <div class="detail">
                        <b><span>{{i.product_name}}</span></b>
                        <br><br>
                        <b>Discription : {{i.discription}}</b>
                        <br>
                        <b>Stock : {{i.stock}}</b>
                        <br>
                    </div>

                </div>
                {% endfor %}
               
               

                
            </div>








        </div>
    </div>
    
</body>

</html>

e_commerce/seller/templates/seller_templates/seller_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>seller home</title>
    <link rel="stylesheet" href="{% static 'css/seller_home.css' %}">
</head>

<body>
    <div class="main">
    
        <div class="container_left">
            <div class="sub">
                <h2>MENU</h2>
            </div>
            <div class="sub"><a href="{% url 'seller:seller_home' %}">Home</a></div>
            <div class="sub"><a href="{% url 'seller:product_catelogue' %}">Product Catelogue</a></div>
            <div class="sub"><a href="{% url 'seller:add_product' %}">Add Product</a></div>
            <div class="sub"><a href="{% url 'seller:change_password' %}">Change Password</a></div>
            <div class="sub"><a href="{% url 'seller:seller_profile' %}">Profile</a></div>
            <div class="sub"><a href="">Recent Orders</a></div>
            <div class="sub"><a href="{% url 'seller:update_stock' %}">Update Stock</a></div>
            <div class="sub"><a href="{% url 'seller:order_history' %}">Order History</a></div>
        </div>
        <div class="container_right">
            <div class="right_box">
                
                <div class="seller_name">
                    <h2 style="color: white;">{{data.seller_first_name}}</h2>
                </div>
                <div class="btn" >
                    <a href="{% url 'seller:logout' %}"><button>LOGOUT</button></a>
                </div>

            </div>

           








        </div>
    </div>
    
</body>

</html>

e_commerce/seller/templates/seller_templates/seller_profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>seller profile</title>
    <style>
        .header {
            text-align: center;
            background-color: beige;
        }

        .details {
            background-color: rgb(245, 245, 245);
            padding: 10px;
            text-align: center;

        }

        .line {
            display: flex;
            justify-content: center;
            flex-direction: row;

        }
    </style>
</head>

<body>
    <div class="header">
        <h1>seller profile</h1>
    </div>
    <div class="details">
        <div class="line">
            <span>Name :</span> <span>{{data.seller_first_name}}</span>
        </div>
        <div class="line">
            <span>Email : <span>{{data.mail}}</span> </span>
        </div>
        <div class="line">
            <span>Shipping Address : <span>{{data.address}}</span> </span>
        </div>
        <div class="line">
            <span>Phone Number : {{data.phone}} </span>
        </div>
    </div>
</body>

</html>

e_commerce/seller/templates/seller_templates/update_stock.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update product</title>
    <link rel="stylesheet" href="{% static 'css/update_stock.css' %}">
</head>

<body>
    <div class="main">
    
        <div class="container_left">
            <div class="sub">
                <h2>MENU</h2>
            </div>
            <div class="sub"><a href="{% url 'seller:seller_home' %}">Home</a></div>
            <div class="sub"><a href="{% url 'seller:product_catelogue' %}">Product Catelogue</a></div>
            <div class="sub"><a href="{% url 'seller:add_product' %}">Add Product</a></div>
            <div class="sub"><a href="{% url 'seller:change_password' %}">Change Password</a></div>
            <div class="sub"><a href="{% url 'seller:seller_profile' %}">Profile</a></div>
            <div class="sub"><a href="">Recent Orders</a></div>
            <div class="sub"><a href="{% url 'seller:update_stock' %}">Update Stock</a></div>
            <div class="sub"><a href="{% url 'seller:order_history' %}">Order History</a></div>
        </div>
        <div class="container_right">
            <div class="seller_name">
                <h3>UPDATE STOCK</h3>
            </div>
            
          
               
               

                <div class="update">
                    <table class="update_table">
                        <tr>
                            <td>
                                <select name="" id="select_p">
                                    <option value="">select </option>
                                    <option value="">product1</option>
                                    <option value="">product2</option>
                                </select>
                            </td>
                            <td>
                                <b>Current stock :<span>xx</span></b>
                            </td>
                            <td>
                                <b>New stock : <span>xx</span></b>
                            </td>
                        </tr>
                        
                    </table>
                </div>
            








        </div>
    </div>
    
</body>

</html>