e_commerce/commen/urls.py
from django.urls import path
from . import views

app_name = 'commen'

urlpatterns = [
    path('project_home', views.project_home, name='project_home'),
    path('customer_sign', views.customer_sign, name='customer_sign'),
    path('customer_login', views.customer_login, name="customer_login"),
    path('seller_sign', views.seller_sign, name="seller_sign"),
    path('seller_login', views.seller_login, name='seller_login'),
    path('email_exist',views.email_exist,name='email_exist')
]

e_commerce/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('cart',views.cart,name="cart"),
    path('change_pass',views.change_pass,name="change_pass"),
    path('customer_home',views.customer_home,name="customer_home"),
    path('customer_signup',views.customer_signup,name="customer_signup"),
    path('order',views.order,name="order"),
    path('product',views.product,name="product"),
    path('profile',views.profile,name="profile"),
    path('logout',views.logout,name="logout"),
    path('product_dtls/ <int:pid>',views.product_dtls,name="product_dtls"),
    path('remove/ <int:pid>',views.remove,name="remove")
    
]

e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('commen/',include ('commen.urls')),
    path('e_admin/',include('e_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_commerce/customer/models.py
from django.db import models
from commen.models import Customer
from seller.models import Product

# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    quantity = models.BigIntegerField()

    class meta:
        db_table = 'cart'

e_commerce/customer/views.py
from django.shortcuts import redirect, render

from commen.models import Customer

from seller.models import Product
from customer.models import Cart
from . decorators import auth_customer
from django.db.models import F



# Create your views here.

@auth_customer
def cart(request):
    cart_data = Cart.objects.filter(customer_id=request.session['customer'])
    cart_data = Cart.objects.annotate(total = F('product__price')*F('quantity'))
    return render(request, 'customer_templates/cart.html',{'data':cart_data} )

def change_pass(request):
    if request.method == 'POST':
        c_pass = request.POST['password']
        customer = Customer.objects.get()

    customer_data = Customer.objects.get(id=request.session['customer'])

    return render(request, 'customer_templates/change_pass.html',{'data':customer_data})

def customer_home(request):
    customer_data = Customer.objects.get(id=request.session['customer'])
    return render(request, 'customer_templates/customer_home.html',{'data':customer_data})

def customer_signup(request):
    return render(request, 'customer_templates/customer_signup.html')

def order(request):
    return render(request, 'customer_templates/order.html')

def product(request):
    product_data = Product.objects.all()
    return render(request, 'customer_templates/products.html',{'data':product_data})

def profile(request):
    msg = ''
    customer_data = Customer.objects.get(id=request.session['customer'])

    if request.method == 'POST':
        new_name = request.POST['edit_name']
        new_mail = request.POST['edit_mail']
        new_address = request.POST['edit_shipping']
        new_phone = request.POST['edit_phone']

        customer1 = Customer.objects.get(id=request.session['customer'])

        customer1 = Customer(customer_name = new_name,
                                         customer_mail = new_mail,customer_addres = new_address,
                                         customer_phone = new_phone
                                         )
        customer1.save()
        msg = 'updated'

    context ={

        'data': customer_data,
        'msg': msg
    }

        
        
    return render(request, 'customer_templates/profile.html',context)
    

def logout(request):
    del request.session['customer']
    request.session.flush()
    return redirect('commen:project_home')

def product_dtls(request,pid):
    msg = ''
    product = Product.objects.get(id=pid)
    if request.method == 'POST':
        quantity = request.POST['qty']
        product_exist = Cart.objects.filter(product = pid,customer = request.session['customer']).exists()
        if not product_exist:
            item = Cart(customer_id = request.session['customer'],product_id = pid,quantity = quantity)
            item.save()
        else:
            msg = 'item already added'
    context = {
        'product':product,
        'msg':msg
    }
    return render(request, 'customer_templates/product_dtls.html',context)

def remove(request,pid):
    remove_data = Cart.objects.filter(product_id=pid)
    remove_data.delete()
    return redirect('customer:cart')

e_commerce/customer/templates/customer_templates/aaa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        
        .header{
            display: flex;
            flex-direction: row;
            width: 100%;
        }
        .header_left{
            text-align: left;
            padding: 2px;
        }
        .header_center{
            text-align: center;
            text-decoration:  none;
            padding: 20px;

        }
        .header_right{
            text-decoration:  none;
            padding: 20px;
            text-align: right;
        }
        .header_center a,.header_right a{
            text-decoration: none;
            padding: 10px;
        }
        .card_holder{
            display: grid;
            grid-template-columns: auto auto auto auto;
        }
        .card img{
            width: 200px;
            height: 200px;
        }
        .prod_list{
            padding: 50px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header_left">
            <h1>Customer</h1>
        </div>
        <div class="header_center">
            <a href="{% url 'customer:products' %}">Products</a>
            <a href="{% url 'customer:orders' %}">Orders</a>
            <a href="{% url 'customer:change_pass' %}">Change Password</a>
        </div>
        <div class="header_right">
            <a href="{% url 'customer:cart' %}">My Cart</a>
            <a href="{% url 'customer:logout' %}">Log Out</a>
            <a href="{% url 'customer:profile' %}">Profile</a>
        </div>
        <br>
        
    </div>
    <div class="prod_list">
        <div class="card_holder">
            {% for product in prod_data %}
        <div class="card " style="width: 18rem;">
            <img src="{{product.prod_image.url}}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">{{product.prod_name}}</h5>
                <p class="card-text">{{product.prod_price}}</p>
                <a href="{% url 'customer:product_details' product.id %}" class="btn btn-primary">Buy Now</a>
                <a href="#" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
</body>
</html>

e_commerce/customer/templates/customer_templates/cart.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .nav {
            width: 100%;
            background-color: black;
            text-align: center;
            padding-top: 20px;
            padding-bottom: 20px;
        }

        .nav b {
            color: white;
            font-size: 30px;
            font-family: sans-serif;
        }

        .main {
            width: 100%;
        }


        .table1 {
            margin-top: 100px;
            margin-left: auto;
            margin-right: auto;

        }

        th {
            background-color: teal;
            padding-left: 40px;
            padding-right: 40px;
            padding-top: 10px;
            padding-bottom: 10px;
        }

        td {
            background-color: black;
            color: white;
            padding-left: 40px;
            padding-right: 40px;
            padding-top: 10px;
            padding-bottom: 10px;
        }
        img{
            width: 50px;
           
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="nav"><b>MY CART</b></div>

        <div class="main">

            <table class="table1">
                <tr>
                    <th>SL</th>
                    <th>PRODUCT IMG</th>
                    <th>NAME</th>
                    <th>PRICE</th>
                    <th>QTY</th>
                    <TH>TOTEL</TH>
                    <th>REMOVE</th>
                </tr>
                
                <tbody>
                   
                    {% for i in data %}
                    <tr>
                       
                        <td>{{forloop.counter}}</td>
                        <td><img src="{{i.product.image.url}}" alt=""></td>
                        <td>{{i.product.product_name}}</td>
                        <td>{{i.product.price}}</td>
                        <td>{{i.quantity}}</td>
                        <td>{{i.total}}</td>
                        <td><a href="{% url 'customer:remove' i.product_id %}"><button>Remove</button></a></td>
                     
                    </tr>
                    {% endfor %}
                </tbody>

               

            </table>

        </div>


    </div>
<a href="{% url 'customer:customer_home' %}">back to homepage</a>

</body>

</html>

e_commerce/customer/templates/customer_templates/change_pass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .header{
            background-color: rgb(201, 201, 201);
            text-align: center;
        }
        .form{
            display: flex;
            justify-content: center;
            padding: 20px;
        }
        .form input{
            width: 150%;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Reset Password</h1>
    </div>
    <div class="form">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="password" name="password" id="password">
            <button type="submit">Reset</button>
        </form>
    </div>
</body>
</html>

e_commerce/customer/templates/customer_templates/customer_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .header{
            display: flex;
            flex-direction: row;
        }
        .header_left{
            text-align: left;
            padding: 2px;
        }
        .header_center{
            text-align: center;
            text-decoration:  none;
            padding: 20px;

        }
        .header_right{
            text-decoration:  none;
            padding: 20px;
            text-align: right;
        }
        .header_center a,.header_right a{
            text-decoration: none;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header_left">
            <h1>customer :{{data.customer_name}}</h1>
        </div>
        <div class="header_center">
            <a href="{% url 'customer:product' %}">Products</a>
            <a href="{% url 'customer:order' %}">Orders</a>
            <a href="{% url 'customer:change_pass' %}">Change Password</a>
        </div>
        <div class="header_right">
            <a href="{% url 'customer:cart' %}">My Cart</a>
            <a href="{% url 'customer:logout' %}">Log Out</a>
            <a href="{% url 'customer:profile' %}">Profile</a>
        </div>
    </div>
    
</body>
</html>

e_commerce/customer/templates/customer_templates/customer_signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    
        #main1 {
            display: flex;
            width: 100%;
            height: 100vh;
            background-color: white;
            justify-content: center;
            align-items: center;
        }

        .div2 {
            width: 50%;
            height: 70vh;
            background-color: rgb(237, 232, 232);
        }
    </style>
</head>

<body>
    <div id="main1">
        <div class="div2">
            <h3 text-align="center">customer regstration</h3>
            <table text-align="center" style="margin-top: 50px;">
                <form action="">
                    <tr>
                        <td><label for="">full name </label></td>
                        <td><input style="width: 200px;" type="text"></td>
                    </tr>

                    <tr>
                        <td><label for="">gender </label></td>
                        <td>male<input type="radio" name="gender" id="">female<input type="radio" name="gender" id="">
                        </td>
                    </tr>
                    <tr>
                        <td><label for="">number</label></td>
                        <td><input style="width: 200px;" type="number"></td>
                    </tr>
                    <tr>
                        <td><label for="">email</label></td>
                        <td><input style="width: 200px;" type="email" name="" id=""></td>
                    </tr>
                    <tr>
                        <td><label for="add">adderss</label></td>
                        <td><input type="text" style="width: 200px;  height: 30px;" name="" id=""></td>
                    </tr>
                    <tr>
                        <td><label for="">password</label></td>
                        <td><input style="width: 200px;" type="password" name="" id=""></td>
                    </tr>
                    <tr>
                        <td>Upload Image</td>
                        <td><input type="file"></td>
                    </tr>
                    <tr>
                        <td align="center" colspan="2"><input type="submit" value="creat new account"></td>
                    </tr>


                </form>
            </table>

        </div>
    </div>





</body>

</html>

e_commerce/customer/templates/customer_templates/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .header{
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>My Orders</h1>
    </div>
    
</body>
</html>

e_commerce/customer/templates/customer_templates/product_dtls.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>


    <div class="card" style="width: 18rem;">
        <img src="{{product.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{product.product_name}}</h5>
          <h5 class="card-title">{{product.price}}</h5>
          <p class="card-text">{{product.discription}}</p>
          <p>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="number" name="qty" placeholder="quantity">
                <button type="submit" class="btn btn-primary">add to cart</button>
                {{msg}}
            </form> 
          </p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>

<a href="{% url 'customer:customer_home' %}">back to homepage</a>
    
</body>
</html>

e_commerce/customer/templates/customer_templates/products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'shoe_static/shoes.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'shoe_static\Bootstrap\css\bootstrap.css'%}">
</head>
<title>Shoes</title>
<link rel="stylesheet" href="">
<style>
    .button {
        /* font-family: "Poppins"; */
        font-weight: bold;
        background-color: transparent;
        border: none;
        color: rgb(0, 0, 0);
        padding: 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        box-shadow: 5px 5px 10px #888;
    }

    #heart {
        outline-style: 1px solid black;
    }

    .header {
        text-align: center;
        background-color: rgb(214, 213, 213);
    }

    .product {
        margin-top: 7px;
        width: 100%;
        display: grid;
        grid-template-columns: auto auto auto auto;
        grid-row-gap: 20px;

    }

    .card {
        width: 250px;
        background-color: whitesmoke;
        margin: 10px;
        border-radius: 7px;
    }

    .b_image {
        padding: 20px;

    }

    .b_image img {
        width: 100%;
        margin-left: auto;
        margin-right: auto;
    }

    .detail {
        font-family: Arial, Helvetica, sans-serif;
        margin-left: 20px;

    }
</style>

<div class="header">
    <h1 style="font-family: sans-serif;">PRODUCT</h1>
</div>
<div class="container">

    <div class="product">

        {% for i in data %}
        <div class="card">
            <div class="b_image">
                <img src="{{i.image.url}}" alt="">
            </div>
            <div class="detail">
                <b><span>{{i.product_name}}</span></b>
                <br><br>
                <b>Discription : {{i.discription}}</b>
                <br>
                <b>Stock :{{i.stock}}</b>
                <br>
                <a href="{% url 'customer:product_dtls' i.id %}"><button>Buy now</button></a>

            </div>
        </div>
        {% endfor %}





    </div>


</div>

<a href="{% url 'customer:customer_home' %}">back to homepage</a>

e_commerce/customer/templates/customer_templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>


    <style>
        .header {
            text-align: center;
            background-color: beige;
        }

        .details {
            background-color: rgb(245, 245, 245);
            padding: 10px;
            text-align: center;

        }

        .line {
            display: flex;
            justify-content: center;
            flex-direction: row;

        }

        #btn {
            margin-top: 20px;

        }

        #body_box {
            margin-top: 30px;
            background-color: whitesmoke;
        }

        .edit {
            display: flex;
            justify-content: center;
            padding: 30px;
        }

        .edit table {
            line-height: 30px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Profile</h1>
    </div>
    <div class="details">
        <div class="line">
            <span>Name :{{data.customer_name}}</span> <span></span>
        </div>
        <div class="line">
            <span>Email :{{data.customer_mail}}</span>
        </div>
        <div class="line">
            <span>Shipping Address :{{data.customer_addres}}</span>
        </div>
        <div class="line">
            <span>Phone Number :{{data.customer_phone}}</span>
        </div>
        <div>
            <button  onclick="editTask()" id="btn">Edit</button>
        </div>
    </div>

    <div id="body_box" style="display: none;">
        <div class="edit">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>
                            <label for="">Name :</label>
                        </td>
                        <td>
                            <input type="text" name="edit_name" id="edit_name" value="{{data.customer_name}}">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="">Email :</label>
                        </td>
                        <td>
                            <input type="email" name="edit_mail" id="edit_mail">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="">Shipping address :</label>
                        </td>
                        <td>
                            <input type="text" name="edit_shipping" id="edit_shipping">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="">Phone :</label>
                        </td>
                        <td>
                            <input type="text" name="edit_phone" id="edit_phone">
                        </td>
                    </tr>
                    <tr>
                        <th>
                        </th>
                        <th>
                            <input type="submit">

                        </th>
                    </tr>

                </table>
            </form>

        </div>




    </div>


    <script>
        function editTask() {
           
            var body_box = document.getElementById('body_box')
            body_box.style.display = ''
            
        }


    </script>
</body>

</html>